---

- block:
    - validate:
        schema:
          type: object
          properties:
            build:
              type: string
              default: stable
            swarm_manager_host:
              type: string
              format: hostname
            swarm_token:
              type: string
            tls_enabled:
              type: boolean
              default: no
            user:
              type: string
              default: ubuntu
          required:
            - build
            - user
        instance: "{{ machine }}"
      register: machine_validated

    - set_fact:
        machine_v: "{{ machine_validated.result }}"

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: install
          build: "{{ machine_v.build }}"
          tls_enabled: "{{ machine_v.tls_enabled }}"
          user: "{{ machine_v.user }}"

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: swarm_worker_node
          manager_host: "{{ machine_v.swarm_manager_host }}"
          token: "{{ machine_v.swarm_token }}"
      when:
        - "'swarm_manager_host' in machine_v"
        - "'swarm_token' in machine_v"

    - import_role:
        name: bedrock.os
      vars:
        os:
          command: reboot_if_required
  tags:
    - machine_docker
