---

- block:
    - validate:
        schema:
          type: object
          properties:
            database_volume_device:
              type: string
            docker_build:
              type: string
              default: stable
            docker_image:
              type: string
            docker_user:
              type: string
              default: ubuntu
            external_network_interface:
              type: string
            keys_volume_device:
              type: string
            network:
              type: string
              enum:
                - mainnet
                - testnet
            stackdriver_enabled:
              type: boolean
              default: no
          required:
            - database_volume_device
            - docker_image
            - keys_volume_device
            - network
            - stackdriver_enabled
        instance: "{{ machine }}"
      register: machine_validated

    - set_fact:
        machine_v: "{{ machine_validated.result }}"

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: install
          database_volume_device: "{{ machine_v.database_volume_device }}"
          docker_build: "{{ machine_v.docker_build }}"
          docker_user: "{{ machine_v.docker_user }}"
          external_network_interface: "{{ machine_v.external_network_interface }}"
          keys_volume_device: "{{ machine_v.keys_volume_device }}"
          network: "{{ machine_v.network }}"
          stackdriver_enabled: "{{ machine_v.stackdriver_enabled }}"

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: container
          image: "{{ machine_v.docker_image }}"
          stackdriver_enabled: "{{ machine_v.stackdriver_enabled }}"
          state: present

    - import_role:
        name: bedrock.os
      vars:
        os:
          command: reboot_if_required

    - name: "Ensure fluentd is running"
      wait_for:
        port: 24224
      when: machine_v.stackdriver_enabled

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: container
          state: started

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: prune_images
  tags:
    - machine_factomd
