---

- block:
    - validate:
        schema:
          type: object
          properties:
            database_volume_device:
              type: string
            external_network_interface:
              type: string
            keys_volume_device:
              type: string
            network:
              type: string
              enum:
                - mainnet
                - testnet
            stackdriver_enabled:
              type: boolean
              default: no
          required:
            - database_volume_device
            - keys_volume_device
            - network
            - stackdriver_enabled
        instance: "{{ machine }}"
      register: machine_validated

    - set_fact:
        machine_v: "{{ machine_validated.result }}"

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: local_volume_from_device
          device: "{{ machine_v.database_volume_device }}"
          mount_point: /mnt/docker_volumes/factom_database
          name: factom_database

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: local_volume_from_device
          device: "{{ machine_v.keys_volume_device }}"
          mount_point: /mnt/docker_volumes/factom_keys
          name: factom_keys

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: install
          external_network_interface: "{{ machine_v.external_network_interface }}"
          network: "{{ machine_v.network }}"
          stackdriver_enabled: "{{ machine_v.stackdriver_enabled }}"

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: container
          image: "{{ machine_v.docker_image }}"
          stackdriver_enabled: "{{ machine_v.stackdriver_enabled }}"
          state: present

    - import_role:
        name: bedrock.os
      vars:
        os:
          command: reboot_if_required

    - import_role:
        name: bedrock.factomd
      vars:
        factomd:
          command: container
          state: started

    - import_role:
        name: bedrock.docker
      vars:
        docker:
          command: prune_images
  tags:
    - machine_factomd
